### ISSUE TITLE
where is the "intrinsic"  located?

### ISSUE THREAD

**Issue by jinsanko** [scivision/piradar#1]
/home/jsk/code/signal_subspace/filters.f90:4.20:

    use, intrinsic:: ieee_arithmetic, only: ieee_is_nan
                    1
Fatal Error: Can't find an intrinsic module named 'ieee_arithmetic' at (1)
make[2]: *** [CMakeFiles/subspace_real.dir/filters.f90.o] Error 1
make[1]: *** [CMakeFiles/subspace_real.dir/all] Error 2
make: *** [all] Error 2

Please help me to check this problem. Thank.

**Comment by scivision** [comment]
`ieee_arithmetic` is a feature of Gfortran >= 5 and other modern Fortran compilers. In this case, the usage was not really needed so I removed it.
